# backend/services/pdf_export.py
"""
AIRP -- Investment Memo PDF Export (T-043)

Converts state["memo_markdown"] (produced by the T-042 memo generator)
into a branded, paginated PDF via WeasyPrint, and writes it to disk.

Pipeline: Markdown -> branded HTML -> PDF bytes -> file on disk.

This module owns the only Markdown->HTML conversion in the codebase.
It is deliberately NOT a general-purpose Markdown parser -- it only
needs to understand the small, fixed subset of Markdown constructs
that backend.services.memo_generator actually produces (H1/H2 headers,
bold, italic, pipe tables, numbered lists, bullet lists, horizontal
rules, paragraphs). Hand-rolling this narrow converter avoids pinning
an extra third-party dependency for a fully-controlled input shape --
the memo's Markdown is generated entirely by AIRP's own code, never by
an end user, so there is no need to handle the full CommonMark spec.

WeasyPrint itself is imported lazily inside the rendering function, not
at module level, following the same defensive pattern already used by
backend/agents/valuation_agent.py for BeautifulSoup/requests: WeasyPrint
depends on system libraries (Pango, Cairo, GDK-Pixbuf) that may not be
installed in every environment (a bare CI runner, a developer machine
without GTK libraries). Importing it lazily means this module -- and
every other module that imports it -- stays importable and unit-testable
even where those system libraries are absent, and `feature_pdf_enabled`
lets the pipeline degrade gracefully rather than fail the whole run.

Acceptance criteria (T-043):
  * PDF downloaded correctly
  * All sections render
  * No layout bugs
  * File size < 500KB

Design decisions
-----------------
Why a hand-rolled Markdown->HTML converter instead of a library?
See module docstring above -- the input is fully controlled and narrow
in scope. A general CommonMark parser would handle far more syntax
than this memo ever produces, at the cost of an extra pinned dependency
with its own transitive requirements. The converter here is a single
linear pass over the markdown's lines using a small set of regexes,
easy to unit test exhaustively against the exact output shape of
memo_generator.py.

Why is file size capped well under 500KB by construction, not just by
testing?
The memo is text-only -- no embedded images, no custom fonts beyond
system defaults, no charts. A 2-3 page text document rendered by
WeasyPrint with simple CSS typically lands in the 30-80KB range. The
500KB ceiling in the acceptance criteria has wide headroom by design;
test_pdf_under_size_limit exists as a regression guard, not because the
margin is tight.

Why does PDF generation never raise, mirroring every other node in this
pipeline?
report_generator_node (T-042) already established that the final nodes
in the pipeline must never fail the whole run. pdf_export_node is now
the new final node -- if it raised, a fully complete, well-reasoned
analysis would be lost over what is fundamentally a presentation-layer
concern. On any failure (WeasyPrint not installed, a system font
library missing, a disk write error), the node logs a warning and
returns memo_pdf_path=None; the Markdown memo (already generated by
T-042) remains fully available regardless.

Public interface
-----------------
  pdf_export_node(state)                 -> dict   LangGraph node
  render_memo_pdf(...)                   -> Optional[Path]
  markdown_to_html(...)                  -> str
  build_branded_html_document(...)       -> str
  resolve_memo_output_dir()              -> Path
  resolve_memo_pdf_path(job_id)          -> Path
"""
import html
import logging
import os
from pathlib import Path
import re
import tempfile
from typing import Any, Optional

try:
    from backend.config import settings as _settings
except Exception:  # config import is best-effort; env vars are the fallback
    _settings = None  # type: ignore[assignment]

# Module-level alias -- patch target in tests:
#   patch("backend.services.pdf_export.settings") replaces this object
settings = _settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module constants
# ---------------------------------------------------------------------------

#: Levels to walk up from this file to reach the repository root.
#: backend/services/pdf_export.py -> services -> backend -> <repo root>
_LEVELS_UP = 3

#: Fallback output directory, used only if settings could not be loaded.
_DEFAULT_MEMO_OUTPUT_DIR = "data/memos"

#: Hard ceiling from the T-043 acceptance criteria. Used by the test
#: suite as a regression guard, not as a runtime-enforced limit -- a
#: text-only memo never approaches this size (see module docstring).
MAX_PDF_SIZE_BYTES = 500 * 1024

_AIRP_BRAND_COLOR = "#1D4ED8"
_AIRP_BRAND_COLOR_DARK = "#1E3A8A"


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def resolve_memo_output_dir() -> Path:
    """
    Resolve the absolute directory where memo PDFs are written.

    Reads settings.memo_output_dir when available (relative paths are
    resolved against the repository root); falls back to
    _DEFAULT_MEMO_OUTPUT_DIR if settings could not be loaded.
    """
    configured = (
        getattr(settings, "memo_output_dir", None) if settings is not None else None
    ) or _DEFAULT_MEMO_OUTPUT_DIR

    configured_path = Path(configured)
    if configured_path.is_absolute():
        return configured_path

    this_file = Path(__file__).resolve()
    repo_root = this_file
    for _ in range(_LEVELS_UP):
        repo_root = repo_root.parent
    return repo_root / configured_path


def resolve_memo_pdf_path(job_id: str) -> Path:
    """
    Resolve the absolute path for a single job's memo PDF.

    Filenames are keyed by job_id so concurrent analyses never collide
    and a re-run of the same job deterministically overwrites its own
    prior PDF rather than accumulating duplicates.
    """
    safe_job_id = re.sub(r"[^A-Za-z0-9_-]", "_", job_id) or "unknown-job"
    return resolve_memo_output_dir() / f"{safe_job_id}.pdf"


# ---------------------------------------------------------------------------
# Markdown -> HTML (narrow converter, scoped to memo_generator.py's output)
# ---------------------------------------------------------------------------


def _inline_markdown_to_html(text: str) -> str:
    """
    Convert inline Markdown spans (bold, italic) within a single line.
    The input text is HTML-escaped first so any literal special
    characters in agent-written prose (e.g. a stray '<' or '&') render
    safely instead of being interpreted as markup.
    """
    escaped = html.escape(text)
    # Bold: **text** -- must run before italic so "**x**" doesn't get
    # partially consumed by the single-asterisk italic pattern first.
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    # Italic: *text* (single asterisk, non-greedy, no longer adjacent
    # to another asterisk since bold was already consumed above).
    escaped = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def _render_table(table_lines: list[str]) -> str:
    """Render a contiguous block of pipe-table lines to an HTML table."""
    rows = [line.strip() for line in table_lines if line.strip()]
    if not rows:
        return ""

    def _split_row(row: str) -> list[str]:
        inner = row.strip().strip("|")
        return [cell.strip() for cell in inner.split("|")]

    header_cells = _split_row(rows[0])
    # rows[1] is the '---|---' separator -- skip it.
    body_rows = [_split_row(r) for r in rows[2:]] if len(rows) > 2 else []

    html_parts = ['<table class="memo-table">', "<thead><tr>"]
    for cell in header_cells:
        html_parts.append(f"<th>{_inline_markdown_to_html(cell)}</th>")
    html_parts.append("</tr></thead><tbody>")
    for body_row in body_rows:
        html_parts.append("<tr>")
        for cell in body_row:
            html_parts.append(f"<td>{_inline_markdown_to_html(cell)}</td>")
        html_parts.append("</tr>")
    html_parts.append("</tbody></table>")
    return "".join(html_parts)


def markdown_to_html(markdown_text: str) -> str:
    """
    Convert the memo's Markdown body to an HTML fragment (no <html>,
    <head>, or <body> wrapper -- see build_branded_html_document for
    the full document). Supports exactly the constructs
    backend.services.memo_generator produces: '# '/'## ' headers,
    '**bold**'/'*italic*', pipe tables, '1. '-style numbered lists,
    '- '-style bullet lists, '---' horizontal rules, and plain
    paragraphs.
    """
    lines = markdown_text.split("\n")
    html_blocks: list[str] = []
    i = 0
    in_ordered_list = False
    in_unordered_list = False

    def _close_lists() -> None:
        nonlocal in_ordered_list, in_unordered_list
        if in_ordered_list:
            html_blocks.append("</ol>")
            in_ordered_list = False
        if in_unordered_list:
            html_blocks.append("</ul>")
            in_unordered_list = False

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            _close_lists()
            i += 1
            continue

        if stripped == "---":
            _close_lists()
            html_blocks.append("<hr/>")
            i += 1
            continue

        if stripped.startswith("# "):
            _close_lists()
            html_blocks.append(f"<h1>{_inline_markdown_to_html(stripped[2:])}</h1>")
            i += 1
            continue

        if stripped.startswith("## "):
            _close_lists()
            html_blocks.append(f"<h2>{_inline_markdown_to_html(stripped[3:])}</h2>")
            i += 1
            continue

        if stripped.startswith("|"):
            _close_lists()
            table_lines = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                table_lines.append(lines[i])
                i += 1
            html_blocks.append(_render_table(table_lines))
            continue

        numbered_match = re.match(r"^\d+\.\s+(.*)$", stripped)
        if numbered_match:
            if in_unordered_list:
                html_blocks.append("</ul>")
                in_unordered_list = False
            if not in_ordered_list:
                html_blocks.append("<ol>")
                in_ordered_list = True
            html_blocks.append(
                f"<li>{_inline_markdown_to_html(numbered_match.group(1))}</li>"
            )
            i += 1
            continue

        if stripped.startswith("- "):
            if in_ordered_list:
                html_blocks.append("</ol>")
                in_ordered_list = False
            if not in_unordered_list:
                html_blocks.append("<ul>")
                in_unordered_list = True
            html_blocks.append(f"<li>{_inline_markdown_to_html(stripped[2:])}</li>")
            i += 1
            continue

        _close_lists()
        html_blocks.append(f"<p>{_inline_markdown_to_html(stripped)}</p>")
        i += 1

    _close_lists()
    return "\n".join(html_blocks)


# ---------------------------------------------------------------------------
# Branded document assembly
# ---------------------------------------------------------------------------


_CSS_TEMPLATE = """
@page {{
    size: A4;
    margin: 2.2cm 1.8cm 2.4cm 1.8cm;
    @top-center {{
        content: "{company_name} -- AIRP Investment Memo";
        font-size: 9px;
        color: #64748B;
        font-family: "Helvetica", "Arial", sans-serif;
    }}
    @bottom-left {{
        content: "Generated {generated_at}";
        font-size: 8px;
        color: #94A3B8;
        font-family: "Helvetica", "Arial", sans-serif;
    }}
    @bottom-center {{
        content: "Page " counter(page) " of " counter(pages);
        font-size: 9px;
        color: #64748B;
        font-family: "Helvetica", "Arial", sans-serif;
    }}
}}

body {{
    font-family: "Helvetica", "Arial", sans-serif;
    font-size: 11px;
    line-height: 1.5;
    color: #1E293B;
}}

h1 {{
    font-size: 18px;
    color: {brand_color_dark};
    border-bottom: 2px solid {brand_color};
    padding-bottom: 6px;
    margin-top: 0;
}}

h2 {{
    font-size: 13px;
    color: {brand_color_dark};
    margin-top: 18px;
    margin-bottom: 6px;
}}

p {{
    margin: 6px 0;
}}

hr {{
    border: none;
    border-top: 1px solid #CBD5E1;
    margin: 14px 0;
}}

table.memo-table {{
    width: 100%;
    border-collapse: collapse;
    margin: 10px 0;
    font-size: 10px;
}}

table.memo-table th, table.memo-table td {{
    border: 1px solid #CBD5E1;
    padding: 6px 8px;
    text-align: left;
}}

table.memo-table th {{
    background-color: #F1F5F9;
    font-weight: bold;
}}

ol, ul {{
    margin: 6px 0;
    padding-left: 22px;
}}

li {{
    margin-bottom: 4px;
}}

strong {{
    color: {brand_color_dark};
}}
"""


def build_branded_html_document(
    memo_markdown: str,
    company_name: str,
    generated_at: str,
) -> str:
    """
    Wrap the memo's converted HTML body in a complete, branded HTML
    document with AIRP-themed CSS, ready for WeasyPrint to render.
    The page-numbering and company-name header come from CSS @page
    rules (rendered by WeasyPrint, not by this function directly) so
    they appear identically on every page without per-page logic here.
    """
    body_html = markdown_to_html(memo_markdown)
    css = _CSS_TEMPLATE.format(
        brand_color=_AIRP_BRAND_COLOR,
        brand_color_dark=_AIRP_BRAND_COLOR_DARK,
        company_name=html.escape(company_name),
        generated_at=html.escape(generated_at),
    )
    return (
        "<!DOCTYPE html>\n"
        '<html>\n<head>\n<meta charset="utf-8">\n'
        f"<style>{css}</style>\n</head>\n<body>\n"
        f"{body_html}\n</body>\n</html>"
    )


# ---------------------------------------------------------------------------
# PDF rendering + atomic write
# ---------------------------------------------------------------------------


def render_memo_pdf(
    memo_markdown: str,
    company_name: str,
    generated_at: str,
    job_id: str,
) -> Optional[Path]:
    """
    Render memo_markdown to a branded PDF and write it to disk.

    Returns the absolute Path written on success, or None if PDF
    generation is disabled, WeasyPrint is unavailable, or any step
    fails. Never raises -- every failure is logged and degrades to
    None so the caller can proceed with the Markdown memo alone.
    """
    pdf_enabled = (
        getattr(settings, "feature_pdf_enabled", True) if settings is not None else True
    )
    if not pdf_enabled:
        logger.info("render_memo_pdf: feature_pdf_enabled=False -- skipping")
        return None

    try:
        from weasyprint import HTML  # noqa: PLC0415 -- lazy, optional system dep
    except (ImportError, OSError) as exc:
        # ImportError: the weasyprint package itself is not installed.
        # OSError: the package IS installed but a native dependency
        # (Pango/Cairo/GDK-Pixbuf, surfaced via cffi's dlopen) could not
        # be loaded -- e.g. installed without its system libraries, or
        # a broken/partial install. Both cases mean PDF export cannot
        # proceed; both must degrade gracefully rather than crash the
        # pipeline.
        logger.warning(
            "render_memo_pdf: WeasyPrint not available -- skipping PDF export "
            "(install weasyprint and its system dependencies: Pango, Cairo, "
            "GDK-Pixbuf): %s",
            exc,
        )
        return None

    try:
        html_document = build_branded_html_document(
            memo_markdown=memo_markdown,
            company_name=company_name,
            generated_at=generated_at,
        )
        pdf_bytes: bytes = HTML(string=html_document).write_pdf()
    except Exception as exc:  # noqa: BLE001 -- this step must never raise
        logger.warning("render_memo_pdf: PDF rendering failed: %s", exc)
        return None

    target = resolve_memo_pdf_path(job_id)

    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        # Atomic write: temp file in the same directory as the target,
        # then os.replace() -- atomic on POSIX, best-effort on Windows.
        # Same pattern as backend/graph/graph_visualisation.py.
        tmp_fd, tmp_path_str = tempfile.mkstemp(
            dir=target.parent,
            prefix=".memo_pdf_tmp_",
            suffix=".pdf",
        )
        try:
            with os.fdopen(tmp_fd, "wb") as tmp_file:
                tmp_file.write(pdf_bytes)
            os.replace(tmp_path_str, str(target))
        except Exception:
            try:
                os.unlink(tmp_path_str)
            except OSError:
                pass
            raise
    except Exception as exc:  # noqa: BLE001 -- this step must never raise
        logger.warning("render_memo_pdf: writing PDF to disk failed: %s", exc)
        return None

    logger.info(
        "render_memo_pdf: wrote %s (%d bytes) for job_id=%s",
        target,
        len(pdf_bytes),
        job_id,
    )
    return target


# ---------------------------------------------------------------------------
# LangGraph node entry point
# ---------------------------------------------------------------------------


def pdf_export_node(state: dict[str, Any]) -> dict[str, Any]:
    """
    LangGraph node entry point (T-043). Reads state["memo_markdown"]
    (written by report_generator_node in T-042) and renders it to a
    branded PDF on disk. Returns {"memo_pdf_path": str | None}.

    Never raises. A missing memo_markdown, a disabled feature flag, a
    missing WeasyPrint installation, or any rendering/write failure all
    degrade to memo_pdf_path=None -- the Markdown memo from T-042
    remains available regardless of PDF export's outcome.
    """
    from datetime import datetime  # noqa: PLC0415 -- avoids module-level import

    # for a stdlib symbol only needed in this one function; keeps the
    # module's import block focused on this module's actual external deps.

    job_id = state.get("job_id", "unknown")
    company_name = state.get("company_name", "Unknown Company")
    memo_markdown = state.get("memo_markdown")

    if not memo_markdown:
        logger.warning(
            "pdf_export_node: no memo_markdown in state for job_id=%s -- "
            "skipping PDF export",
            job_id,
        )
        return {"memo_pdf_path": None}

    generated_at = datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")

    pdf_path = render_memo_pdf(
        memo_markdown=memo_markdown,
        company_name=company_name,
        generated_at=generated_at,
        job_id=job_id,
    )

    return {"memo_pdf_path": str(pdf_path) if pdf_path is not None else None}


__all__ = [
    "MAX_PDF_SIZE_BYTES",
    "pdf_export_node",
    "render_memo_pdf",
    "markdown_to_html",
    "build_branded_html_document",
    "resolve_memo_output_dir",
    "resolve_memo_pdf_path",
]
