// frontend/src/components/landing/LandingFooter.tsx
// Landing page (T-055) — the "footer" acceptance criterion. This is the
// page's *content* footer (link columns + disclaimer), rendered inside
// <main> as the last section of the landing page. It is intentionally
// separate from RootLayout's slim chrome footer ("Built as a portfolio
// project...") which still renders below it on every route -- the same
// two-tier pattern (rich footer content, then a thin copyright bar) most
// marketing sites use.
//
// Includes a plain-language disclaimer: AIRP's verdicts are a portfolio
// project's simulated output, not real financial advice, and the footer
// says so directly rather than leaving that implicit.

import { Link } from "react-router-dom";

const REPO_URL = "https://github.com/Aditya083103/AIRP---Autonomous-Investment-Research-Platform";

interface FooterLink {
  readonly label: string;
  readonly href: string;
}

interface FooterColumn {
  readonly heading: string;
  readonly links: readonly FooterLink[];
}

const COLUMNS: readonly FooterColumn[] = [
  {
    heading: "Product",
    links: [
      { label: "How it works", href: "#how-it-works" },
      { label: "The committee", href: "#committee" },
      { label: "Run an analysis", href: "/analysis" },
    ],
  },
  {
    heading: "Project",
    links: [{ label: "Source on GitHub", href: REPO_URL }],
  },
];

const LINK_CLASSES = "text-sm text-muted transition-colors hover:text-ink";

/**
 * Renders a footer link with the right tag for its target: a same-page
 * `<a href="#...">` for hash anchors (so the browser's native scroll-to
 * behaviour applies -- react-router's `Link` does not scroll on hash-only
 * `to` values), a real `<a target="_blank">` for the external GitHub URL,
 * and a router `Link` for every other internal route.
 */
function FooterLinkItem({ link }: { link: FooterLink }): JSX.Element {
  if (link.href.startsWith("http")) {
    return (
      <a href={link.href} target="_blank" rel="noreferrer" className={LINK_CLASSES}>
        {link.label}
      </a>
    );
  }

  if (link.href.startsWith("#")) {
    return (
      <a href={link.href} className={LINK_CLASSES}>
        {link.label}
      </a>
    );
  }

  return (
    <Link to={link.href} className={LINK_CLASSES}>
      {link.label}
    </Link>
  );
}

/** The landing page's content footer: link columns and an investment-advice disclaimer. */
export function LandingFooter(): JSX.Element {
  return (
    <footer className="border-t border-line py-12">
      <div className="grid gap-10 sm:grid-cols-[2fr,1fr,1fr]">
        <div>
          <p className="font-mono text-sm font-semibold text-ink">AIRP</p>
          <p className="mt-2 max-w-xs text-sm leading-relaxed text-muted">
            Autonomous Investment Research Platform — an 8-agent investment committee, built as a
            portfolio project.
          </p>
        </div>

        {COLUMNS.map((column) => (
          <div key={column.heading}>
            <p className="text-xs font-semibold uppercase tracking-wide text-ink">
              {column.heading}
            </p>
            <ul className="mt-3 space-y-2">
              {column.links.map((link) => (
                <li key={link.label}>
                  <FooterLinkItem link={link} />
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <p className="mt-10 border-t border-line pt-6 text-xs leading-relaxed text-muted">
        Educational portfolio project. Verdicts, conviction scores, and Investment Memos are
        generated by simulated AI agents for demonstration purposes and are not investment advice.
      </p>
    </footer>
  );
}
